# Generated by Django 4.1.4 on 2022-12-16 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attractions', '0002_rename_descricao_attractions_description_and_more'),
        ('core', '0003_rename_aprovado_touristhotspot_approved_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='touristhotspot',
            name='attractions',
            field=models.ManyToManyField(to='attractions.attractions'),
        ),
    ]
