# Generated by Django 4.1.4 on 2022-12-16 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0001_initial'),
        ('attractions', '0003_rename_attractions_attraction'),
        ('core', '0005_alter_touristhotspot_attractions'),
    ]

    operations = [
        migrations.AddField(
            model_name='touristhotspot',
            name='comments',
            field=models.ManyToManyField(to='comments.comment'),
        ),
        migrations.AlterField(
            model_name='touristhotspot',
            name='attractions',
            field=models.ManyToManyField(to='attractions.attraction'),
        ),
    ]
