# Generated by Django 4.1.4 on 2022-12-16 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0001_initial'),
        ('core', '0006_touristhotspot_comments_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='touristhotspot',
            name='assessments',
            field=models.ManyToManyField(to='assessments.assessment'),
        ),
    ]
