# Generated by Django 4.1.4 on 2022-12-17 00:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('addresses', '0001_initial'),
        ('core', '0007_touristhotspot_assessments'),
    ]

    operations = [
        migrations.AddField(
            model_name='touristhotspot',
            name='Addresses',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='addresses.address'),
            preserve_default=False,
        ),
    ]
