# Generated by Django 4.1.4 on 2022-12-17 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0001_initial'),
        ('assessments', '0001_initial'),
        ('attractions', '0003_rename_attractions_attraction'),
        ('core', '0009_alter_touristhotspot_addresses'),
    ]

    operations = [
        migrations.AlterField(
            model_name='touristhotspot',
            name='assessments',
            field=models.ManyToManyField(blank=True, null=True, to='assessments.assessment'),
        ),
        migrations.AlterField(
            model_name='touristhotspot',
            name='attractions',
            field=models.ManyToManyField(blank=True, null=True, to='attractions.attraction'),
        ),
        migrations.AlterField(
            model_name='touristhotspot',
            name='comments',
            field=models.ManyToManyField(blank=True, null=True, to='comments.comment'),
        ),
    ]
