# Generated by Django 4.1.4 on 2022-12-20 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_touristhotspot_assessments_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='touristhotspot',
            name='Photo',
            field=models.ImageField(blank=True, null=True, upload_to='pontos_turisticos'),
        ),
    ]
