# Generated by Django 4.1.4 on 2022-12-29 17:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_touristhotspot_photo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='touristhotspot',
            old_name='Photo',
            new_name='photo',
        ),
    ]
