# Generated by Django 4.1.4 on 2022-12-29 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0001_initial'),
        ('attractions', '0004_attraction_photo'),
        ('comments', '0001_initial'),
        ('core', '0012_rename_photo_touristhotspot_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='touristhotspot',
            name='assessments',
            field=models.ManyToManyField(to='assessments.assessment'),
        ),
        migrations.AlterField(
            model_name='touristhotspot',
            name='attractions',
            field=models.ManyToManyField(to='attractions.attraction'),
        ),
        migrations.AlterField(
            model_name='touristhotspot',
            name='comments',
            field=models.ManyToManyField(to='comments.comment'),
        ),
    ]
