# Generated by Django 4.1.4 on 2022-12-16 21:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attractions', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attractions',
            old_name='descricao',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='attractions',
            old_name='idade_minima',
            new_name='minimum_age',
        ),
        migrations.RenameField(
            model_name='attractions',
            old_name='nome',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='attractions',
            old_name='horario_func',
            new_name='opening_hours',
        ),
    ]
