# Generated by Django 4.1.4 on 2022-12-16 22:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attractions', '0002_rename_descricao_attractions_description_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Attractions',
            new_name='Attraction',
        ),
    ]
