# Generated by Django 4.1.4 on 2022-12-20 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attractions', '0003_rename_attractions_attraction'),
    ]

    operations = [
        migrations.AddField(
            model_name='attraction',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='atracoes'),
        ),
    ]
